/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

plugins {
    java
    application
    kotlin("jvm")
    kotlin("plugin.serialization") version kotlinVersion
    id("org.openjfx.javafxplugin") version javafxPluginVersion
    id("org.beryx.jlink") version jlinkPluginVersion
}

repositories {
    mavenCentral()
    jcenter()
}

dependencies {
    implementation(kotlin("stdlib-jdk8"))
//    implementation(project(":proxy"))
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutinesVersion")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-runtime:$serializationVersion")
}

application {
    mainModule.set("com.abysl.chaos.manager")
    mainClassName = "com.abysl.chaos.manager.ManagerKt"
}

javafx {
    version = "14"
    modules = listOf("javafx.controls", "javafx.web", "javafx.fxml")
}

jlink {
    options.set(listOf("--strip-debug", "--compress", "2", "--no-header-files", "--no-man-pages"))

    launcher {
        name = "Chaos"
    }

    jpackage {
        resourceDir = file("$buildDir/resources")
        imageOptions = listOf("--icon", "src/main/resources/com/abysl/chaos/manager/images/chaos.ico")
        installerOptions = listOf("--win-per-user-install", "--win-dir-chooser", "--win-menu")
        appVersion = project.version.toString()
    }
}

tasks.jpackageImage {
    doLast {
        copy {
            from("bin/")
            include("*.exe")
            include("*.dll")
            into("$buildDir/jpackage/Chaos/bin/")
        }
    }
}


tasks.classes {
    dependsOn("createBin")
}

tasks.clean {
    doFirst {
        delete("bin/")
    }
}

task("createBin") {
    dependsOn(":inject:installRelease")
    dependsOn(":exalt:linkRelease")
    doLast {
        copy {
            from(project(":inject").buildDir.path + "/exe/main/release/inject.exe")
            into("bin/")
        }
        copy {
            from(project(":exalt").buildDir.path + "/lib/main/release/exalt.dll")
            into("bin/")
        }
        copy {
            from("C:\\Users\\Andrew\\programming\\rotmg\\chaoshook\\chaoshook\\x64\\Release\\chaoshook.dll")
            into("bin/")
        }
    }
}
