/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample C++ project to get you started.
 * For more details take a look at the Building C++ applications and libraries chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.5.1/userguide/building_cpp_projects.html
 */

plugins {
    // Apply the cpp-application plugin to add support for building C++ executables
    `cpp-application`

    // Apply the cpp-unit-test plugin to add support for building and running C++ test executables
    `cpp-unit-test`
}


// Set the target operating system and architecture for this application
application {
    targetMachines.add(machines.windows.x86_64)
}

task<Exec>("run"){
//    dependsOn(tasks.named("installDebug"))
    commandLine("$buildDir/exe/main/debug/${project.name}.exe")
}

val createRelease by tasks.registering {
    dependsOn("installRelease")
    val exe = file("$buildDir/exe/main/release/${project.name}.exe")
    outputs.file(exe)
}

