/*
 * This C++ source file was generated by the Gradle 'init' task.
 */
#ifndef EXALT_H
#define EXALT_H

#ifdef _WIN32
#define EXALT_EXPORT_FUNC __declspec(dllexport)
#else
#define EXALT_EXPORT_FUNC
#endif

#include <string>

namespace exalt {
    class Greeter {
        public:
        std::string EXALT_EXPORT_FUNC greeting();
    };
}

#endif
