/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

import java.io.StringReader
import kotlin.text.StringBuilder
import org.w3c.dom.*

plugins {
    java
    application
    kotlin("jvm")
    id("org.beryx.jlink") version "2.21.0"
}

repositories {
    mavenCentral()
    jcenter()
}

dependencies {
    implementation(kotlin("stdlib-jdk8"))
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutinesVersion")
    implementation("io.ktor:ktor-server-netty:$ktorVersion")
    implementation("org.bouncycastle:bcprov-jdk15on:1.66")

}

application {
    mainModule.set("com.abysl.chaos.proxy")
    mainClassName = "com.abysl.chaos.proxy.ProxyKt"
}

//javafx {
//    version = "14"
//    modules = listOf("javafx.controls", "javafx.web", "javafx.fxml")
//}

jlink {
    options.set(listOf("--strip-debug", "--compress", "2", "--no-header-files", "--no-man-pages"))

    launcher {
        name = "Chaos Proxy"
    }

    jpackage {
        resourceDir = file("$buildDir/resources")
        imageOptions = listOf("--icon", "src/main/resources/com/abysl/chaos/proxy/images/chaos.ico")
        installerOptions = listOf("--win-per-user-install", "--win-dir-chooser", "--win-menu")
        appVersion = project.version.toString()
    }
}

task("transpile", JavaExec::class) {
    main = "com.abysl.chaos.proxy.tools.TranspilerKt"
    classpath = sourceSets["main"].runtimeClasspath
}

